"""
Audit log data access for Bifrost.

This module provides functions to write committed permission changes to the audit log
table and read audit entries with filtering support.

The audit log table (<schema>.Bifrost_audit_log) is created automatically on first
connection if it doesn't exist. All administrators share the same audit log.

Usage:
    from src.db.audit import (
        ensure_audit_log_table,
        write_audit_entries,
        fetch_audit_entries,
        fetch_recent_audit_entries
    )
    from src.db.connection import create_connection
    from src.models.audit_entry import AuditEntry
    from datetime import datetime, timezone
    
    conn = create_connection(config)
    try:
        # Ensure table exists
        ensure_audit_log_table(conn, schema="dbo")
        
        # Write entries
        entry = AuditEntry(
            id=0,  # Auto-generated by database
            administrator="DOMAIN\\alice",
            affected_user="bob",
            schema_name="dbo",
            object_name="Orders",
            permission_type="SELECT",
            action="GRANT",
            previous_state="NONE",
            new_state="GRANT",
            changed_at=datetime.now(timezone.utc),
            explanation="GRANT SELECT on dbo.Orders to bob"
        )
        write_audit_entries(conn, [entry])
        conn.commit()
        
        # Read entries
        entries = fetch_recent_audit_entries(conn, limit=50)
    finally:
        conn.close()
"""

import pyodbc
from datetime import datetime
from typing import Optional
from src.models.audit_entry import AuditEntry


def ensure_audit_log_table(conn: pyodbc.Connection, schema: str = "dbo") -> None:
    """
    Ensure the Bifrost_audit_log table exists, creating it if necessary.
    
    Args:
        conn: Active database connection
        schema: Schema name (from config.schema, default "dbo")
    
    Raises:
        pyodbc.Error: If table creation fails
    
    Table:
        <schema>.Bifrost_audit_log
    
    Columns:
        id BIGINT IDENTITY PK
        administrator NVARCHAR(128) - SYSTEM_USER at commit time
        affected_user NVARCHAR(128) - Database principal whose permission changed
        schema_name NVARCHAR(128)
        object_name NVARCHAR(128)
        permission_type NVARCHAR(64) - SELECT, INSERT, etc.
        action NVARCHAR(16) - GRANT, DENY, REVOKE
        previous_state NVARCHAR(16) - GRANT, DENY, NONE
        new_state NVARCHAR(16) - GRANT, DENY, NONE
        changed_at DATETIME2(3) DEFAULT GETUTCDATE()
        explanation NVARCHAR(500) - Auto-generated description
    
    Indexes:
        PK_Bifrost_audit_log (id)
        IX_Bifrost_audit_log_changed_at (changed_at DESC)
        IX_Bifrost_audit_log_affected_user (affected_user, changed_at DESC)
        IX_Bifrost_audit_log_object (schema_name, object_name, changed_at DESC)
    
    Note:
        - Called automatically on first connection by the App controller
        - Schema is created first if it doesn't exist (see connection.ensure_schema_exists)
        - Check constraints enforce action and state values
    
    Example:
        >>> conn = create_connection(config)
        >>> ensure_audit_log_table(conn, schema="dbo")
    """
    cursor = conn.cursor()
    try:
        # Check if table exists
        cursor.execute(
            """
            SELECT 1
            FROM sys.tables t
            JOIN sys.schemas s ON s.schema_id = t.schema_id
            WHERE s.name = ? AND t.name = 'Bifrost_audit_log'
            """,
            (schema,)
        )
        
        if cursor.fetchone():
            return  # Table already exists
        
        # Validate schema name before DDL
        import re
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", schema):
            raise ValueError(f"Invalid schema name: {schema}")
        
        # Create table (dynamic SQL required for schema name substitution)
        create_table_stmt = f"""
        CREATE TABLE [{schema}].[Bifrost_audit_log] (
            id               BIGINT         IDENTITY(1,1)  NOT NULL,
            administrator    NVARCHAR(128)                 NOT NULL,
            affected_user    NVARCHAR(128)                 NOT NULL,
            schema_name      NVARCHAR(128)                 NOT NULL,
            object_name      NVARCHAR(128)                 NOT NULL,
            permission_type  NVARCHAR(64)                  NOT NULL,
            action           NVARCHAR(16)                  NOT NULL,
            previous_state   NVARCHAR(16)                  NOT NULL,
            new_state        NVARCHAR(16)                  NOT NULL,
            changed_at       DATETIME2(3)                  NOT NULL   DEFAULT (GETUTCDATE()),
            explanation      NVARCHAR(500)                 NULL,
            
            CONSTRAINT [PK_Bifrost_audit_log] PRIMARY KEY CLUSTERED (id),
            CONSTRAINT [CK_Bifrost_audit_log_action]         CHECK (action         IN (N'GRANT', N'DENY', N'REVOKE')),
            CONSTRAINT [CK_Bifrost_audit_log_previous_state] CHECK (previous_state IN (N'GRANT', N'DENY', N'NONE')),
            CONSTRAINT [CK_Bifrost_audit_log_new_state]      CHECK (new_state      IN (N'GRANT', N'DENY', N'NONE'))
        );
        
        CREATE NONCLUSTERED INDEX [IX_Bifrost_audit_log_changed_at]
            ON [{schema}].[Bifrost_audit_log] (changed_at DESC);
        
        CREATE NONCLUSTERED INDEX [IX_Bifrost_audit_log_affected_user]
            ON [{schema}].[Bifrost_audit_log] (affected_user, changed_at DESC);
        
        CREATE NONCLUSTERED INDEX [IX_Bifrost_audit_log_object]
            ON [{schema}].[Bifrost_audit_log] (schema_name, object_name, changed_at DESC);
        """
        
        cursor.execute(create_table_stmt)
        conn.commit()
    
    finally:
        cursor.close()


def write_audit_entries(
    conn: pyodbc.Connection,
    entries: list[AuditEntry],
    schema: str = "dbo"
) -> list[int]:
    """
    Write a batch of audit entries to the audit log table.
    
    Args:
        conn: Active database connection
        entries: List of AuditEntry instances to write
        schema: Schema name (from config.schema, default "dbo")
    
    Returns:
        list[int]: List of auto-generated IDs for the inserted entries
    
    Note:
        - changed_at is set by the database (GETUTCDATE()) if not provided
        - Caller must commit transaction (conn.commit())
        - Administrator field is typically SYSTEM_USER (populated by caller)
    
    Example:
        >>> conn = create_connection(config)
        >>> entry = AuditEntry(...)
        >>> ids = write_audit_entries(conn, [entry], schema="dbo")
        >>> conn.commit()
        >>> print(ids)
        [1, 2, 3]
    """
    cursor = conn.cursor()
    try:
        # Validate schema name before dynamic SQL
        import re
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", schema):
            raise ValueError(f"Invalid schema name: {schema}")
        
        ids = []
        for entry in entries:
            stmt = f"""
                INSERT INTO [{schema}].[Bifrost_audit_log] (
                    administrator,
                    affected_user,
                    schema_name,
                    object_name,
                    permission_type,
                    action,
                    previous_state,
                    new_state,
                    changed_at,
                    explanation
                )
                OUTPUT INSERTED.id
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """
            
            cursor.execute(
                stmt,
                (
                    entry.administrator,
                    entry.affected_user,
                    entry.schema_name,
                    entry.object_name,
                    entry.permission_type,
                    entry.action,
                    entry.previous_state,
                    entry.new_state,
                    entry.changed_at,
                    entry.explanation,
                )
            )
            
            # Get the auto-generated ID
            row = cursor.fetchone()
            if row:
                ids.append(row[0])
        
        return ids
    
    finally:
        cursor.close()


def fetch_audit_entries(
    conn: pyodbc.Connection,
    schema: str = "dbo",
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    affected_user: Optional[str] = None,
    schema_name: Optional[str] = None,
    object_name: Optional[str] = None,
    limit: Optional[int] = None
) -> list[AuditEntry]:
    """
    Fetch audit entries with optional filtering.
    
    Args:
        conn: Active database connection
        schema: Schema name for audit log table (from config.schema)
        start_date: Filter entries on or after this date (inclusive)
        end_date: Filter entries on or before this date (inclusive)
        affected_user: Filter by affected user login name (exact match)
        schema_name: Filter by object schema name (exact match)
        object_name: Filter by object name (exact match)
        limit: Maximum number of entries to return (most recent first)
    
    Returns:
        list[AuditEntry]: Audit entries matching filters (newest first)
    
    Example:
        >>> from datetime import datetime, timedelta, timezone
        >>> conn = create_connection(config)
        >>> yesterday = datetime.now(timezone.utc) - timedelta(days=1)
        >>> entries = fetch_audit_entries(
        ...     conn,
        ...     schema="dbo",
        ...     start_date=yesterday,
        ...     affected_user="alice",
        ...     limit=50
        ... )
        >>> len(entries)
        12
    """
    cursor = conn.cursor()
    try:
        # Validate schema name before dynamic SQL
        import re
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", schema):
            raise ValueError(f"Invalid schema name: {schema}")
        
        # Build query with filters
        where_clauses = []
        params = []
        
        if start_date:
            where_clauses.append("changed_at >= ?")
            params.append(start_date)
        
        if end_date:
            where_clauses.append("changed_at <= ?")
            params.append(end_date)
        
        if affected_user:
            where_clauses.append("affected_user = ?")
            params.append(affected_user)
        
        if schema_name:
            where_clauses.append("schema_name = ?")
            params.append(schema_name)
        
        if object_name:
            where_clauses.append("object_name = ?")
            params.append(object_name)
        
        where_clause = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""
        limit_clause = f"TOP {limit}" if limit else ""
        
        query = f"""
            SELECT {limit_clause}
                id,
                administrator,
                affected_user,
                schema_name,
                object_name,
                permission_type,
                action,
                previous_state,
                new_state,
                changed_at,
                explanation
            FROM [{schema}].[Bifrost_audit_log]
            {where_clause}
            ORDER BY changed_at DESC, id DESC
        """
        
        cursor.execute(query, params)
        
        entries = []
        for row in cursor.fetchall():
            entry = AuditEntry(
                id=row.id,
                administrator=row.administrator,
                affected_user=row.affected_user,
                schema_name=row.schema_name,
                object_name=row.object_name,
                permission_type=row.permission_type,
                action=row.action,
                previous_state=row.previous_state,
                new_state=row.new_state,
                changed_at=row.changed_at,
                explanation=row.explanation or "",
            )
            entries.append(entry)
        
        return entries
    
    finally:
        cursor.close()


def fetch_recent_audit_entries(
    conn: pyodbc.Connection,
    schema: str = "dbo",
    limit: int = 50
) -> list[AuditEntry]:
    """
    Fetch the most recent audit entries (no filtering).
    
    Args:
        conn: Active database connection
        schema: Schema name for audit log table
        limit: Maximum number of entries (default 50)
    
    Returns:
        list[AuditEntry]: Most recent audit entries (newest first)
    
    Example:
        >>> conn = create_connection(config)
        >>> recent = fetch_recent_audit_entries(conn, limit=50)
        >>> len(recent)
        50
        >>> recent[0].changed_at > recent[-1].changed_at
        True
    """
    return fetch_audit_entries(conn, schema=schema, limit=limit)


def get_audit_entry_count(
    conn: pyodbc.Connection,
    schema: str = "dbo"
) -> int:
    """
    Get the total count of audit entries.
    
    Args:
        conn: Active database connection
        schema: Schema name for audit log table
    
    Returns:
        int: Total number of audit entries
    
    Example:
        >>> conn = create_connection(config)
        >>> get_audit_entry_count(conn, schema="dbo")
        1247
    """
    cursor = conn.cursor()
    try:
        # Validate schema name
        import re
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", schema):
            raise ValueError(f"Invalid schema name: {schema}")
        
        query = f"SELECT COUNT(*) FROM [{schema}].[Bifrost_audit_log]"
        cursor.execute(query)
        row = cursor.fetchone()
        return row[0] if row else 0
    
    finally:
        cursor.close()
